//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.7.2558.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/project", IsNullable=false)]
public partial class Project {
    
    private string saveVersionField;
    
    private string buildNumberField;
    
    private string nameField;
    
    private string gUIDField;
    
    private string titleField;
    
    private string companyField;
    
    private string creationDateField;
    
    private string lastSavedField;
    
    private string scheduleFromStartField;
    
    private string startDateField;
    
    private string finishDateField;
    
    private string fYStartDateField;
    
    private string criticalSlackLimitField;
    
    private string currencyDigitsField;
    
    private string currencySymbolField;
    
    private string currencyCodeField;
    
    private string currencySymbolPositionField;
    
    private string calendarUIDField;
    
    private string defaultStartTimeField;
    
    private string defaultFinishTimeField;
    
    private string minutesPerDayField;
    
    private string minutesPerWeekField;
    
    private string daysPerMonthField;
    
    private string defaultTaskTypeField;
    
    private string defaultFixedCostAccrualField;
    
    private string defaultStandardRateField;
    
    private string defaultOvertimeRateField;
    
    private string durationFormatField;
    
    private string workFormatField;
    
    private string editableActualCostsField;
    
    private string honorConstraintsField;
    
    private string insertedProjectsLikeSummaryField;
    
    private string multipleCriticalPathsField;
    
    private string newTasksEffortDrivenField;
    
    private string newTasksEstimatedField;
    
    private string splitsInProgressTasksField;
    
    private string spreadActualCostField;
    
    private string spreadPercentCompleteField;
    
    private string taskUpdatesResourceField;
    
    private string fiscalYearStartField;
    
    private string weekStartDayField;
    
    private string moveCompletedEndsBackField;
    
    private string moveRemainingStartsBackField;
    
    private string moveRemainingStartsForwardField;
    
    private string moveCompletedEndsForwardField;
    
    private string baselineForEarnedValueField;
    
    private string autoAddNewResourcesAndTasksField;
    
    private string currentDateField;
    
    private string microsoftProjectServerURLField;
    
    private string autolinkField;
    
    private string newTaskStartDateField;
    
    private string newTasksAreManualField;
    
    private string defaultTaskEVMethodField;
    
    private string projectExternallyEditedField;
    
    private string extendedCreationDateField;
    
    private string actualsInSyncField;
    
    private string removeFilePropertiesField;
    
    private string adminProjectField;
    
    private string updateManuallyScheduledTasksWhenEditingLinksField;
    
    private string keepTaskOnNearestWorkingTimeWhenMadeAutoScheduledField;
    
    private string sprintLengthField;
    
    private string agileModeField;
    
    private string mapsField;
    
    private string reportsField;
    
    private string dataLinksField;
    
    private string vBAProjectsField;
    
    private string outlineCodesField;
    
    private string wBSMasksField;
    
    private string extendedAttributesField;
    
    private ProjectViewsView[][] viewsField;
    
    private ProjectFiltersFilter[][] filtersField;
    
    private ProjectGroupsGroup[][] groupsField;
    
    private ProjectTablesTable[][] tablesField;
    
    private ProjectDrawingsDrawing[][] drawingsField;
    
    private ProjectCalendarsCalendar[][] calendarsField;
    
    private ProjectTasksTask[][] tasksField;
    
    private ProjectResourcesResource[][] resourcesField;
    
    private ProjectAssignmentsAssignment[][] assignmentsField;
    
    private ProjectBoardColumnsBoardColumn[][] boardColumnsField;
    
    private ProjectSprintsSprint[][] sprintsField;
    
    /// <remarks/>
    public string SaveVersion {
        get {
            return this.saveVersionField;
        }
        set {
            this.saveVersionField = value;
        }
    }
    
    /// <remarks/>
    public string BuildNumber {
        get {
            return this.buildNumberField;
        }
        set {
            this.buildNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string Company {
        get {
            return this.companyField;
        }
        set {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    public string CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    public string LastSaved {
        get {
            return this.lastSavedField;
        }
        set {
            this.lastSavedField = value;
        }
    }
    
    /// <remarks/>
    public string ScheduleFromStart {
        get {
            return this.scheduleFromStartField;
        }
        set {
            this.scheduleFromStartField = value;
        }
    }
    
    /// <remarks/>
    public string StartDate {
        get {
            return this.startDateField;
        }
        set {
            this.startDateField = value;
        }
    }
    
    /// <remarks/>
    public string FinishDate {
        get {
            return this.finishDateField;
        }
        set {
            this.finishDateField = value;
        }
    }
    
    /// <remarks/>
    public string FYStartDate {
        get {
            return this.fYStartDateField;
        }
        set {
            this.fYStartDateField = value;
        }
    }
    
    /// <remarks/>
    public string CriticalSlackLimit {
        get {
            return this.criticalSlackLimitField;
        }
        set {
            this.criticalSlackLimitField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencyDigits {
        get {
            return this.currencyDigitsField;
        }
        set {
            this.currencyDigitsField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencySymbol {
        get {
            return this.currencySymbolField;
        }
        set {
            this.currencySymbolField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CurrencySymbolPosition {
        get {
            return this.currencySymbolPositionField;
        }
        set {
            this.currencySymbolPositionField = value;
        }
    }
    
    /// <remarks/>
    public string CalendarUID {
        get {
            return this.calendarUIDField;
        }
        set {
            this.calendarUIDField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultStartTime {
        get {
            return this.defaultStartTimeField;
        }
        set {
            this.defaultStartTimeField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultFinishTime {
        get {
            return this.defaultFinishTimeField;
        }
        set {
            this.defaultFinishTimeField = value;
        }
    }
    
    /// <remarks/>
    public string MinutesPerDay {
        get {
            return this.minutesPerDayField;
        }
        set {
            this.minutesPerDayField = value;
        }
    }
    
    /// <remarks/>
    public string MinutesPerWeek {
        get {
            return this.minutesPerWeekField;
        }
        set {
            this.minutesPerWeekField = value;
        }
    }
    
    /// <remarks/>
    public string DaysPerMonth {
        get {
            return this.daysPerMonthField;
        }
        set {
            this.daysPerMonthField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultTaskType {
        get {
            return this.defaultTaskTypeField;
        }
        set {
            this.defaultTaskTypeField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultFixedCostAccrual {
        get {
            return this.defaultFixedCostAccrualField;
        }
        set {
            this.defaultFixedCostAccrualField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultStandardRate {
        get {
            return this.defaultStandardRateField;
        }
        set {
            this.defaultStandardRateField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultOvertimeRate {
        get {
            return this.defaultOvertimeRateField;
        }
        set {
            this.defaultOvertimeRateField = value;
        }
    }
    
    /// <remarks/>
    public string DurationFormat {
        get {
            return this.durationFormatField;
        }
        set {
            this.durationFormatField = value;
        }
    }
    
    /// <remarks/>
    public string WorkFormat {
        get {
            return this.workFormatField;
        }
        set {
            this.workFormatField = value;
        }
    }
    
    /// <remarks/>
    public string EditableActualCosts {
        get {
            return this.editableActualCostsField;
        }
        set {
            this.editableActualCostsField = value;
        }
    }
    
    /// <remarks/>
    public string HonorConstraints {
        get {
            return this.honorConstraintsField;
        }
        set {
            this.honorConstraintsField = value;
        }
    }
    
    /// <remarks/>
    public string InsertedProjectsLikeSummary {
        get {
            return this.insertedProjectsLikeSummaryField;
        }
        set {
            this.insertedProjectsLikeSummaryField = value;
        }
    }
    
    /// <remarks/>
    public string MultipleCriticalPaths {
        get {
            return this.multipleCriticalPathsField;
        }
        set {
            this.multipleCriticalPathsField = value;
        }
    }
    
    /// <remarks/>
    public string NewTasksEffortDriven {
        get {
            return this.newTasksEffortDrivenField;
        }
        set {
            this.newTasksEffortDrivenField = value;
        }
    }
    
    /// <remarks/>
    public string NewTasksEstimated {
        get {
            return this.newTasksEstimatedField;
        }
        set {
            this.newTasksEstimatedField = value;
        }
    }
    
    /// <remarks/>
    public string SplitsInProgressTasks {
        get {
            return this.splitsInProgressTasksField;
        }
        set {
            this.splitsInProgressTasksField = value;
        }
    }
    
    /// <remarks/>
    public string SpreadActualCost {
        get {
            return this.spreadActualCostField;
        }
        set {
            this.spreadActualCostField = value;
        }
    }
    
    /// <remarks/>
    public string SpreadPercentComplete {
        get {
            return this.spreadPercentCompleteField;
        }
        set {
            this.spreadPercentCompleteField = value;
        }
    }
    
    /// <remarks/>
    public string TaskUpdatesResource {
        get {
            return this.taskUpdatesResourceField;
        }
        set {
            this.taskUpdatesResourceField = value;
        }
    }
    
    /// <remarks/>
    public string FiscalYearStart {
        get {
            return this.fiscalYearStartField;
        }
        set {
            this.fiscalYearStartField = value;
        }
    }
    
    /// <remarks/>
    public string WeekStartDay {
        get {
            return this.weekStartDayField;
        }
        set {
            this.weekStartDayField = value;
        }
    }
    
    /// <remarks/>
    public string MoveCompletedEndsBack {
        get {
            return this.moveCompletedEndsBackField;
        }
        set {
            this.moveCompletedEndsBackField = value;
        }
    }
    
    /// <remarks/>
    public string MoveRemainingStartsBack {
        get {
            return this.moveRemainingStartsBackField;
        }
        set {
            this.moveRemainingStartsBackField = value;
        }
    }
    
    /// <remarks/>
    public string MoveRemainingStartsForward {
        get {
            return this.moveRemainingStartsForwardField;
        }
        set {
            this.moveRemainingStartsForwardField = value;
        }
    }
    
    /// <remarks/>
    public string MoveCompletedEndsForward {
        get {
            return this.moveCompletedEndsForwardField;
        }
        set {
            this.moveCompletedEndsForwardField = value;
        }
    }
    
    /// <remarks/>
    public string BaselineForEarnedValue {
        get {
            return this.baselineForEarnedValueField;
        }
        set {
            this.baselineForEarnedValueField = value;
        }
    }
    
    /// <remarks/>
    public string AutoAddNewResourcesAndTasks {
        get {
            return this.autoAddNewResourcesAndTasksField;
        }
        set {
            this.autoAddNewResourcesAndTasksField = value;
        }
    }
    
    /// <remarks/>
    public string CurrentDate {
        get {
            return this.currentDateField;
        }
        set {
            this.currentDateField = value;
        }
    }
    
    /// <remarks/>
    public string MicrosoftProjectServerURL {
        get {
            return this.microsoftProjectServerURLField;
        }
        set {
            this.microsoftProjectServerURLField = value;
        }
    }
    
    /// <remarks/>
    public string Autolink {
        get {
            return this.autolinkField;
        }
        set {
            this.autolinkField = value;
        }
    }
    
    /// <remarks/>
    public string NewTaskStartDate {
        get {
            return this.newTaskStartDateField;
        }
        set {
            this.newTaskStartDateField = value;
        }
    }
    
    /// <remarks/>
    public string NewTasksAreManual {
        get {
            return this.newTasksAreManualField;
        }
        set {
            this.newTasksAreManualField = value;
        }
    }
    
    /// <remarks/>
    public string DefaultTaskEVMethod {
        get {
            return this.defaultTaskEVMethodField;
        }
        set {
            this.defaultTaskEVMethodField = value;
        }
    }
    
    /// <remarks/>
    public string ProjectExternallyEdited {
        get {
            return this.projectExternallyEditedField;
        }
        set {
            this.projectExternallyEditedField = value;
        }
    }
    
    /// <remarks/>
    public string ExtendedCreationDate {
        get {
            return this.extendedCreationDateField;
        }
        set {
            this.extendedCreationDateField = value;
        }
    }
    
    /// <remarks/>
    public string ActualsInSync {
        get {
            return this.actualsInSyncField;
        }
        set {
            this.actualsInSyncField = value;
        }
    }
    
    /// <remarks/>
    public string RemoveFileProperties {
        get {
            return this.removeFilePropertiesField;
        }
        set {
            this.removeFilePropertiesField = value;
        }
    }
    
    /// <remarks/>
    public string AdminProject {
        get {
            return this.adminProjectField;
        }
        set {
            this.adminProjectField = value;
        }
    }
    
    /// <remarks/>
    public string UpdateManuallyScheduledTasksWhenEditingLinks {
        get {
            return this.updateManuallyScheduledTasksWhenEditingLinksField;
        }
        set {
            this.updateManuallyScheduledTasksWhenEditingLinksField = value;
        }
    }
    
    /// <remarks/>
    public string KeepTaskOnNearestWorkingTimeWhenMadeAutoScheduled {
        get {
            return this.keepTaskOnNearestWorkingTimeWhenMadeAutoScheduledField;
        }
        set {
            this.keepTaskOnNearestWorkingTimeWhenMadeAutoScheduledField = value;
        }
    }
    
    /// <remarks/>
    public string SprintLength {
        get {
            return this.sprintLengthField;
        }
        set {
            this.sprintLengthField = value;
        }
    }
    
    /// <remarks/>
    public string AgileMode {
        get {
            return this.agileModeField;
        }
        set {
            this.agileModeField = value;
        }
    }
    
    /// <remarks/>
    public string Maps {
        get {
            return this.mapsField;
        }
        set {
            this.mapsField = value;
        }
    }
    
    /// <remarks/>
    public string Reports {
        get {
            return this.reportsField;
        }
        set {
            this.reportsField = value;
        }
    }
    
    /// <remarks/>
    public string DataLinks {
        get {
            return this.dataLinksField;
        }
        set {
            this.dataLinksField = value;
        }
    }
    
    /// <remarks/>
    public string VBAProjects {
        get {
            return this.vBAProjectsField;
        }
        set {
            this.vBAProjectsField = value;
        }
    }
    
    /// <remarks/>
    public string OutlineCodes {
        get {
            return this.outlineCodesField;
        }
        set {
            this.outlineCodesField = value;
        }
    }
    
    /// <remarks/>
    public string WBSMasks {
        get {
            return this.wBSMasksField;
        }
        set {
            this.wBSMasksField = value;
        }
    }
    
    /// <remarks/>
    public string ExtendedAttributes {
        get {
            return this.extendedAttributesField;
        }
        set {
            this.extendedAttributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("View", typeof(ProjectViewsView), IsNullable=false)]
    public ProjectViewsView[][] Views {
        get {
            return this.viewsField;
        }
        set {
            this.viewsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Filter", typeof(ProjectFiltersFilter), IsNullable=false)]
    public ProjectFiltersFilter[][] Filters {
        get {
            return this.filtersField;
        }
        set {
            this.filtersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Group", typeof(ProjectGroupsGroup), IsNullable=false)]
    public ProjectGroupsGroup[][] Groups {
        get {
            return this.groupsField;
        }
        set {
            this.groupsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Table", typeof(ProjectTablesTable), IsNullable=false)]
    public ProjectTablesTable[][] Tables {
        get {
            return this.tablesField;
        }
        set {
            this.tablesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Drawing", typeof(ProjectDrawingsDrawing), IsNullable=false)]
    public ProjectDrawingsDrawing[][] Drawings {
        get {
            return this.drawingsField;
        }
        set {
            this.drawingsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Calendar", typeof(ProjectCalendarsCalendar), IsNullable=false)]
    public ProjectCalendarsCalendar[][] Calendars {
        get {
            return this.calendarsField;
        }
        set {
            this.calendarsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Task", typeof(ProjectTasksTask), IsNullable=false)]
    public ProjectTasksTask[][] Tasks {
        get {
            return this.tasksField;
        }
        set {
            this.tasksField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Resource", typeof(ProjectResourcesResource), IsNullable=false)]
    public ProjectResourcesResource[][] Resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Assignment", typeof(ProjectAssignmentsAssignment), IsNullable=false)]
    public ProjectAssignmentsAssignment[][] Assignments {
        get {
            return this.assignmentsField;
        }
        set {
            this.assignmentsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("BoardColumn", typeof(ProjectBoardColumnsBoardColumn), IsNullable=false)]
    public ProjectBoardColumnsBoardColumn[][] BoardColumns {
        get {
            return this.boardColumnsField;
        }
        set {
            this.boardColumnsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Sprint", typeof(ProjectSprintsSprint), IsNullable=false)]
    public ProjectSprintsSprint[][] Sprints {
        get {
            return this.sprintsField;
        }
        set {
            this.sprintsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectViewsView {
    
    private string nameField;
    
    private string isCustomizedField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string IsCustomized {
        get {
            return this.isCustomizedField;
        }
        set {
            this.isCustomizedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectFiltersFilter {
    
    private string nameField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectGroupsGroup {
    
    private string nameField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectTablesTable {
    
    private string nameField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectDrawingsDrawing {
    
    private string nameField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectCalendarsCalendar {
    
    private string uIDField;
    
    private string gUIDField;
    
    private string nameField;
    
    private string isBaseCalendarField;
    
    private string isBaselineCalendarField;
    
    private string baseCalendarUIDField;
    
    private ProjectCalendarsCalendarWeekDaysWeekDay[][] weekDaysField;
    
    /// <remarks/>
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string IsBaseCalendar {
        get {
            return this.isBaseCalendarField;
        }
        set {
            this.isBaseCalendarField = value;
        }
    }
    
    /// <remarks/>
    public string IsBaselineCalendar {
        get {
            return this.isBaselineCalendarField;
        }
        set {
            this.isBaselineCalendarField = value;
        }
    }
    
    /// <remarks/>
    public string BaseCalendarUID {
        get {
            return this.baseCalendarUIDField;
        }
        set {
            this.baseCalendarUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WeekDay", typeof(ProjectCalendarsCalendarWeekDaysWeekDay), IsNullable=false)]
    public ProjectCalendarsCalendarWeekDaysWeekDay[][] WeekDays {
        get {
            return this.weekDaysField;
        }
        set {
            this.weekDaysField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectCalendarsCalendarWeekDaysWeekDay {
    
    private string dayTypeField;
    
    private string dayWorkingField;
    
    private ProjectCalendarsCalendarWeekDaysWeekDayWorkingTimesWorkingTime[][] workingTimesField;
    
    /// <remarks/>
    public string DayType {
        get {
            return this.dayTypeField;
        }
        set {
            this.dayTypeField = value;
        }
    }
    
    /// <remarks/>
    public string DayWorking {
        get {
            return this.dayWorkingField;
        }
        set {
            this.dayWorkingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("WorkingTime", typeof(ProjectCalendarsCalendarWeekDaysWeekDayWorkingTimesWorkingTime), IsNullable=false)]
    public ProjectCalendarsCalendarWeekDaysWeekDayWorkingTimesWorkingTime[][] WorkingTimes {
        get {
            return this.workingTimesField;
        }
        set {
            this.workingTimesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectCalendarsCalendarWeekDaysWeekDayWorkingTimesWorkingTime {
    
    private string fromTimeField;
    
    private string toTimeField;
    
    /// <remarks/>
    public string FromTime {
        get {
            return this.fromTimeField;
        }
        set {
            this.fromTimeField = value;
        }
    }
    
    /// <remarks/>
    public string ToTime {
        get {
            return this.toTimeField;
        }
        set {
            this.toTimeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectTasksTask {
    
    private string uIDField;
    
    private string gUIDField;
    
    private string idField;
    
    private string nameField;
    
    private string activeField;
    
    private string manualField;
    
    private string typeField;
    
    private string isNullField;
    
    private string createDateField;
    
    private string wBSField;
    
    private string outlineNumberField;
    
    private string outlineLevelField;
    
    private string priorityField;
    
    private string startField;
    
    private string finishField;
    
    private string durationField;
    
    private string manualStartField;
    
    private string manualFinishField;
    
    private string manualDurationField;
    
    private string durationFormatField;
    
    private string freeformDurationFormatField;
    
    private string workField;
    
    private string resumeValidField;
    
    private string effortDrivenField;
    
    private string recurringField;
    
    private string overAllocatedField;
    
    private string estimatedField;
    
    private string milestoneField;
    
    private string summaryField;
    
    private string displayAsSummaryField;
    
    private string criticalField;
    
    private string isSubprojectField;
    
    private string isSubprojectReadOnlyField;
    
    private string externalTaskField;
    
    private string earlyStartField;
    
    private string earlyFinishField;
    
    private string lateStartField;
    
    private string lateFinishField;
    
    private string startVarianceField;
    
    private string finishVarianceField;
    
    private string workVarianceField;
    
    private string freeSlackField;
    
    private string totalSlackField;
    
    private string startSlackField;
    
    private string finishSlackField;
    
    private string fixedCostField;
    
    private string fixedCostAccrualField;
    
    private string percentCompleteField;
    
    private string percentWorkCompleteField;
    
    private string costField;
    
    private string overtimeCostField;
    
    private string overtimeWorkField;
    
    private string actualDurationField;
    
    private string actualCostField;
    
    private string actualOvertimeCostField;
    
    private string actualWorkField;
    
    private string actualOvertimeWorkField;
    
    private string regularWorkField;
    
    private string remainingDurationField;
    
    private string remainingCostField;
    
    private string remainingWorkField;
    
    private string remainingOvertimeCostField;
    
    private string remainingOvertimeWorkField;
    
    private string aCWPField;
    
    private string cvField;
    
    private string constraintTypeField;
    
    private string calendarUIDField;
    
    private string levelAssignmentsField;
    
    private string levelingCanSplitField;
    
    private string levelingDelayField;
    
    private string levelingDelayFormatField;
    
    private string ignoreResourceCalendarField;
    
    private string hideBarField;
    
    private string rollupField;
    
    private string bCWSField;
    
    private string bCWPField;
    
    private string physicalPercentCompleteField;
    
    private string earnedValueMethodField;
    
    private string isPublishedField;
    
    private string commitmentTypeField;
    
    private string boardStatusColumnOrderingIDField;
    
    private string sprintColumnOrderingIDField;
    
    private string nextAvailableBoardStatusColumnOrderingIDField;
    
    private string nextAvailableSprintOrderingIDField;
    
    private string sprintUIDField;
    
    private string boardColumnUIDField;
    
    private ProjectTasksTaskPredecessorLink[] predecessorLinkField;
    
    /// <remarks/>
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Active {
        get {
            return this.activeField;
        }
        set {
            this.activeField = value;
        }
    }
    
    /// <remarks/>
    public string Manual {
        get {
            return this.manualField;
        }
        set {
            this.manualField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string IsNull {
        get {
            return this.isNullField;
        }
        set {
            this.isNullField = value;
        }
    }
    
    /// <remarks/>
    public string CreateDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    public string WBS {
        get {
            return this.wBSField;
        }
        set {
            this.wBSField = value;
        }
    }
    
    /// <remarks/>
    public string OutlineNumber {
        get {
            return this.outlineNumberField;
        }
        set {
            this.outlineNumberField = value;
        }
    }
    
    /// <remarks/>
    public string OutlineLevel {
        get {
            return this.outlineLevelField;
        }
        set {
            this.outlineLevelField = value;
        }
    }
    
    /// <remarks/>
    public string Priority {
        get {
            return this.priorityField;
        }
        set {
            this.priorityField = value;
        }
    }
    
    /// <remarks/>
    public string Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    public string Finish {
        get {
            return this.finishField;
        }
        set {
            this.finishField = value;
        }
    }
    
    /// <remarks/>
    public string Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
    
    /// <remarks/>
    public string ManualStart {
        get {
            return this.manualStartField;
        }
        set {
            this.manualStartField = value;
        }
    }
    
    /// <remarks/>
    public string ManualFinish {
        get {
            return this.manualFinishField;
        }
        set {
            this.manualFinishField = value;
        }
    }
    
    /// <remarks/>
    public string ManualDuration {
        get {
            return this.manualDurationField;
        }
        set {
            this.manualDurationField = value;
        }
    }
    
    /// <remarks/>
    public string DurationFormat {
        get {
            return this.durationFormatField;
        }
        set {
            this.durationFormatField = value;
        }
    }
    
    /// <remarks/>
    public string FreeformDurationFormat {
        get {
            return this.freeformDurationFormatField;
        }
        set {
            this.freeformDurationFormatField = value;
        }
    }
    
    /// <remarks/>
    public string Work {
        get {
            return this.workField;
        }
        set {
            this.workField = value;
        }
    }
    
    /// <remarks/>
    public string ResumeValid {
        get {
            return this.resumeValidField;
        }
        set {
            this.resumeValidField = value;
        }
    }
    
    /// <remarks/>
    public string EffortDriven {
        get {
            return this.effortDrivenField;
        }
        set {
            this.effortDrivenField = value;
        }
    }
    
    /// <remarks/>
    public string Recurring {
        get {
            return this.recurringField;
        }
        set {
            this.recurringField = value;
        }
    }
    
    /// <remarks/>
    public string OverAllocated {
        get {
            return this.overAllocatedField;
        }
        set {
            this.overAllocatedField = value;
        }
    }
    
    /// <remarks/>
    public string Estimated {
        get {
            return this.estimatedField;
        }
        set {
            this.estimatedField = value;
        }
    }
    
    /// <remarks/>
    public string Milestone {
        get {
            return this.milestoneField;
        }
        set {
            this.milestoneField = value;
        }
    }
    
    /// <remarks/>
    public string Summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
    
    /// <remarks/>
    public string DisplayAsSummary {
        get {
            return this.displayAsSummaryField;
        }
        set {
            this.displayAsSummaryField = value;
        }
    }
    
    /// <remarks/>
    public string Critical {
        get {
            return this.criticalField;
        }
        set {
            this.criticalField = value;
        }
    }
    
    /// <remarks/>
    public string IsSubproject {
        get {
            return this.isSubprojectField;
        }
        set {
            this.isSubprojectField = value;
        }
    }
    
    /// <remarks/>
    public string IsSubprojectReadOnly {
        get {
            return this.isSubprojectReadOnlyField;
        }
        set {
            this.isSubprojectReadOnlyField = value;
        }
    }
    
    /// <remarks/>
    public string ExternalTask {
        get {
            return this.externalTaskField;
        }
        set {
            this.externalTaskField = value;
        }
    }
    
    /// <remarks/>
    public string EarlyStart {
        get {
            return this.earlyStartField;
        }
        set {
            this.earlyStartField = value;
        }
    }
    
    /// <remarks/>
    public string EarlyFinish {
        get {
            return this.earlyFinishField;
        }
        set {
            this.earlyFinishField = value;
        }
    }
    
    /// <remarks/>
    public string LateStart {
        get {
            return this.lateStartField;
        }
        set {
            this.lateStartField = value;
        }
    }
    
    /// <remarks/>
    public string LateFinish {
        get {
            return this.lateFinishField;
        }
        set {
            this.lateFinishField = value;
        }
    }
    
    /// <remarks/>
    public string StartVariance {
        get {
            return this.startVarianceField;
        }
        set {
            this.startVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string FinishVariance {
        get {
            return this.finishVarianceField;
        }
        set {
            this.finishVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string WorkVariance {
        get {
            return this.workVarianceField;
        }
        set {
            this.workVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string FreeSlack {
        get {
            return this.freeSlackField;
        }
        set {
            this.freeSlackField = value;
        }
    }
    
    /// <remarks/>
    public string TotalSlack {
        get {
            return this.totalSlackField;
        }
        set {
            this.totalSlackField = value;
        }
    }
    
    /// <remarks/>
    public string StartSlack {
        get {
            return this.startSlackField;
        }
        set {
            this.startSlackField = value;
        }
    }
    
    /// <remarks/>
    public string FinishSlack {
        get {
            return this.finishSlackField;
        }
        set {
            this.finishSlackField = value;
        }
    }
    
    /// <remarks/>
    public string FixedCost {
        get {
            return this.fixedCostField;
        }
        set {
            this.fixedCostField = value;
        }
    }
    
    /// <remarks/>
    public string FixedCostAccrual {
        get {
            return this.fixedCostAccrualField;
        }
        set {
            this.fixedCostAccrualField = value;
        }
    }
    
    /// <remarks/>
    public string PercentComplete {
        get {
            return this.percentCompleteField;
        }
        set {
            this.percentCompleteField = value;
        }
    }
    
    /// <remarks/>
    public string PercentWorkComplete {
        get {
            return this.percentWorkCompleteField;
        }
        set {
            this.percentWorkCompleteField = value;
        }
    }
    
    /// <remarks/>
    public string Cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    public string OvertimeCost {
        get {
            return this.overtimeCostField;
        }
        set {
            this.overtimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string OvertimeWork {
        get {
            return this.overtimeWorkField;
        }
        set {
            this.overtimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string ActualDuration {
        get {
            return this.actualDurationField;
        }
        set {
            this.actualDurationField = value;
        }
    }
    
    /// <remarks/>
    public string ActualCost {
        get {
            return this.actualCostField;
        }
        set {
            this.actualCostField = value;
        }
    }
    
    /// <remarks/>
    public string ActualOvertimeCost {
        get {
            return this.actualOvertimeCostField;
        }
        set {
            this.actualOvertimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string ActualWork {
        get {
            return this.actualWorkField;
        }
        set {
            this.actualWorkField = value;
        }
    }
    
    /// <remarks/>
    public string ActualOvertimeWork {
        get {
            return this.actualOvertimeWorkField;
        }
        set {
            this.actualOvertimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string RegularWork {
        get {
            return this.regularWorkField;
        }
        set {
            this.regularWorkField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingDuration {
        get {
            return this.remainingDurationField;
        }
        set {
            this.remainingDurationField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingCost {
        get {
            return this.remainingCostField;
        }
        set {
            this.remainingCostField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingWork {
        get {
            return this.remainingWorkField;
        }
        set {
            this.remainingWorkField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingOvertimeCost {
        get {
            return this.remainingOvertimeCostField;
        }
        set {
            this.remainingOvertimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingOvertimeWork {
        get {
            return this.remainingOvertimeWorkField;
        }
        set {
            this.remainingOvertimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string ACWP {
        get {
            return this.aCWPField;
        }
        set {
            this.aCWPField = value;
        }
    }
    
    /// <remarks/>
    public string CV {
        get {
            return this.cvField;
        }
        set {
            this.cvField = value;
        }
    }
    
    /// <remarks/>
    public string ConstraintType {
        get {
            return this.constraintTypeField;
        }
        set {
            this.constraintTypeField = value;
        }
    }
    
    /// <remarks/>
    public string CalendarUID {
        get {
            return this.calendarUIDField;
        }
        set {
            this.calendarUIDField = value;
        }
    }
    
    /// <remarks/>
    public string LevelAssignments {
        get {
            return this.levelAssignmentsField;
        }
        set {
            this.levelAssignmentsField = value;
        }
    }
    
    /// <remarks/>
    public string LevelingCanSplit {
        get {
            return this.levelingCanSplitField;
        }
        set {
            this.levelingCanSplitField = value;
        }
    }
    
    /// <remarks/>
    public string LevelingDelay {
        get {
            return this.levelingDelayField;
        }
        set {
            this.levelingDelayField = value;
        }
    }
    
    /// <remarks/>
    public string LevelingDelayFormat {
        get {
            return this.levelingDelayFormatField;
        }
        set {
            this.levelingDelayFormatField = value;
        }
    }
    
    /// <remarks/>
    public string IgnoreResourceCalendar {
        get {
            return this.ignoreResourceCalendarField;
        }
        set {
            this.ignoreResourceCalendarField = value;
        }
    }
    
    /// <remarks/>
    public string HideBar {
        get {
            return this.hideBarField;
        }
        set {
            this.hideBarField = value;
        }
    }
    
    /// <remarks/>
    public string Rollup {
        get {
            return this.rollupField;
        }
        set {
            this.rollupField = value;
        }
    }
    
    /// <remarks/>
    public string BCWS {
        get {
            return this.bCWSField;
        }
        set {
            this.bCWSField = value;
        }
    }
    
    /// <remarks/>
    public string BCWP {
        get {
            return this.bCWPField;
        }
        set {
            this.bCWPField = value;
        }
    }
    
    /// <remarks/>
    public string PhysicalPercentComplete {
        get {
            return this.physicalPercentCompleteField;
        }
        set {
            this.physicalPercentCompleteField = value;
        }
    }
    
    /// <remarks/>
    public string EarnedValueMethod {
        get {
            return this.earnedValueMethodField;
        }
        set {
            this.earnedValueMethodField = value;
        }
    }
    
    /// <remarks/>
    public string IsPublished {
        get {
            return this.isPublishedField;
        }
        set {
            this.isPublishedField = value;
        }
    }
    
    /// <remarks/>
    public string CommitmentType {
        get {
            return this.commitmentTypeField;
        }
        set {
            this.commitmentTypeField = value;
        }
    }
    
    /// <remarks/>
    public string BoardStatusColumnOrderingID {
        get {
            return this.boardStatusColumnOrderingIDField;
        }
        set {
            this.boardStatusColumnOrderingIDField = value;
        }
    }
    
    /// <remarks/>
    public string SprintColumnOrderingID {
        get {
            return this.sprintColumnOrderingIDField;
        }
        set {
            this.sprintColumnOrderingIDField = value;
        }
    }
    
    /// <remarks/>
    public string NextAvailableBoardStatusColumnOrderingID {
        get {
            return this.nextAvailableBoardStatusColumnOrderingIDField;
        }
        set {
            this.nextAvailableBoardStatusColumnOrderingIDField = value;
        }
    }
    
    /// <remarks/>
    public string NextAvailableSprintOrderingID {
        get {
            return this.nextAvailableSprintOrderingIDField;
        }
        set {
            this.nextAvailableSprintOrderingIDField = value;
        }
    }
    
    /// <remarks/>
    public string SprintUID {
        get {
            return this.sprintUIDField;
        }
        set {
            this.sprintUIDField = value;
        }
    }
    
    /// <remarks/>
    public string BoardColumnUID {
        get {
            return this.boardColumnUIDField;
        }
        set {
            this.boardColumnUIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PredecessorLink")]
    public ProjectTasksTaskPredecessorLink[] PredecessorLink {
        get {
            return this.predecessorLinkField;
        }
        set {
            this.predecessorLinkField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectTasksTaskPredecessorLink {
    
    private string predecessorUIDField;
    
    private string typeField;
    
    private string crossProjectField;
    
    private string linkLagField;
    
    private string lagFormatField;
    
    /// <remarks/>
    public string PredecessorUID {
        get {
            return this.predecessorUIDField;
        }
        set {
            this.predecessorUIDField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string CrossProject {
        get {
            return this.crossProjectField;
        }
        set {
            this.crossProjectField = value;
        }
    }
    
    /// <remarks/>
    public string LinkLag {
        get {
            return this.linkLagField;
        }
        set {
            this.linkLagField = value;
        }
    }
    
    /// <remarks/>
    public string LagFormat {
        get {
            return this.lagFormatField;
        }
        set {
            this.lagFormatField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectResourcesResource {
    
    private string uIDField;
    
    private string gUIDField;
    
    private string idField;
    
    private string nameField;
    
    private string typeField;
    
    private string isNullField;
    
    private string initialsField;
    
    private string maxUnitsField;
    
    private string peakUnitsField;
    
    private string overAllocatedField;
    
    private string canLevelField;
    
    private string accrueAtField;
    
    private string workField;
    
    private string regularWorkField;
    
    private string overtimeWorkField;
    
    private string actualWorkField;
    
    private string remainingWorkField;
    
    private string actualOvertimeWorkField;
    
    private string remainingOvertimeWorkField;
    
    private string percentWorkCompleteField;
    
    private string standardRateField;
    
    private string standardRateFormatField;
    
    private string costField;
    
    private string overtimeRateField;
    
    private string overtimeRateFormatField;
    
    private string overtimeCostField;
    
    private string costPerUseField;
    
    private string actualCostField;
    
    private string actualOvertimeCostField;
    
    private string remainingCostField;
    
    private string remainingOvertimeCostField;
    
    private string workVarianceField;
    
    private string costVarianceField;
    
    private string svField;
    
    private string cvField;
    
    private string aCWPField;
    
    private string calendarUIDField;
    
    private string bCWSField;
    
    private string bCWPField;
    
    private string isGenericField;
    
    private string isInactiveField;
    
    private string isEnterpriseField;
    
    private string bookingTypeField;
    
    private string creationDateField;
    
    private string isCostResourceField;
    
    private string isBudgetField;
    
    /// <remarks/>
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string IsNull {
        get {
            return this.isNullField;
        }
        set {
            this.isNullField = value;
        }
    }
    
    /// <remarks/>
    public string Initials {
        get {
            return this.initialsField;
        }
        set {
            this.initialsField = value;
        }
    }
    
    /// <remarks/>
    public string MaxUnits {
        get {
            return this.maxUnitsField;
        }
        set {
            this.maxUnitsField = value;
        }
    }
    
    /// <remarks/>
    public string PeakUnits {
        get {
            return this.peakUnitsField;
        }
        set {
            this.peakUnitsField = value;
        }
    }
    
    /// <remarks/>
    public string OverAllocated {
        get {
            return this.overAllocatedField;
        }
        set {
            this.overAllocatedField = value;
        }
    }
    
    /// <remarks/>
    public string CanLevel {
        get {
            return this.canLevelField;
        }
        set {
            this.canLevelField = value;
        }
    }
    
    /// <remarks/>
    public string AccrueAt {
        get {
            return this.accrueAtField;
        }
        set {
            this.accrueAtField = value;
        }
    }
    
    /// <remarks/>
    public string Work {
        get {
            return this.workField;
        }
        set {
            this.workField = value;
        }
    }
    
    /// <remarks/>
    public string RegularWork {
        get {
            return this.regularWorkField;
        }
        set {
            this.regularWorkField = value;
        }
    }
    
    /// <remarks/>
    public string OvertimeWork {
        get {
            return this.overtimeWorkField;
        }
        set {
            this.overtimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string ActualWork {
        get {
            return this.actualWorkField;
        }
        set {
            this.actualWorkField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingWork {
        get {
            return this.remainingWorkField;
        }
        set {
            this.remainingWorkField = value;
        }
    }
    
    /// <remarks/>
    public string ActualOvertimeWork {
        get {
            return this.actualOvertimeWorkField;
        }
        set {
            this.actualOvertimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingOvertimeWork {
        get {
            return this.remainingOvertimeWorkField;
        }
        set {
            this.remainingOvertimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string PercentWorkComplete {
        get {
            return this.percentWorkCompleteField;
        }
        set {
            this.percentWorkCompleteField = value;
        }
    }
    
    /// <remarks/>
    public string StandardRate {
        get {
            return this.standardRateField;
        }
        set {
            this.standardRateField = value;
        }
    }
    
    /// <remarks/>
    public string StandardRateFormat {
        get {
            return this.standardRateFormatField;
        }
        set {
            this.standardRateFormatField = value;
        }
    }
    
    /// <remarks/>
    public string Cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    public string OvertimeRate {
        get {
            return this.overtimeRateField;
        }
        set {
            this.overtimeRateField = value;
        }
    }
    
    /// <remarks/>
    public string OvertimeRateFormat {
        get {
            return this.overtimeRateFormatField;
        }
        set {
            this.overtimeRateFormatField = value;
        }
    }
    
    /// <remarks/>
    public string OvertimeCost {
        get {
            return this.overtimeCostField;
        }
        set {
            this.overtimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string CostPerUse {
        get {
            return this.costPerUseField;
        }
        set {
            this.costPerUseField = value;
        }
    }
    
    /// <remarks/>
    public string ActualCost {
        get {
            return this.actualCostField;
        }
        set {
            this.actualCostField = value;
        }
    }
    
    /// <remarks/>
    public string ActualOvertimeCost {
        get {
            return this.actualOvertimeCostField;
        }
        set {
            this.actualOvertimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingCost {
        get {
            return this.remainingCostField;
        }
        set {
            this.remainingCostField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingOvertimeCost {
        get {
            return this.remainingOvertimeCostField;
        }
        set {
            this.remainingOvertimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string WorkVariance {
        get {
            return this.workVarianceField;
        }
        set {
            this.workVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string CostVariance {
        get {
            return this.costVarianceField;
        }
        set {
            this.costVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string SV {
        get {
            return this.svField;
        }
        set {
            this.svField = value;
        }
    }
    
    /// <remarks/>
    public string CV {
        get {
            return this.cvField;
        }
        set {
            this.cvField = value;
        }
    }
    
    /// <remarks/>
    public string ACWP {
        get {
            return this.aCWPField;
        }
        set {
            this.aCWPField = value;
        }
    }
    
    /// <remarks/>
    public string CalendarUID {
        get {
            return this.calendarUIDField;
        }
        set {
            this.calendarUIDField = value;
        }
    }
    
    /// <remarks/>
    public string BCWS {
        get {
            return this.bCWSField;
        }
        set {
            this.bCWSField = value;
        }
    }
    
    /// <remarks/>
    public string BCWP {
        get {
            return this.bCWPField;
        }
        set {
            this.bCWPField = value;
        }
    }
    
    /// <remarks/>
    public string IsGeneric {
        get {
            return this.isGenericField;
        }
        set {
            this.isGenericField = value;
        }
    }
    
    /// <remarks/>
    public string IsInactive {
        get {
            return this.isInactiveField;
        }
        set {
            this.isInactiveField = value;
        }
    }
    
    /// <remarks/>
    public string IsEnterprise {
        get {
            return this.isEnterpriseField;
        }
        set {
            this.isEnterpriseField = value;
        }
    }
    
    /// <remarks/>
    public string BookingType {
        get {
            return this.bookingTypeField;
        }
        set {
            this.bookingTypeField = value;
        }
    }
    
    /// <remarks/>
    public string CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    public string IsCostResource {
        get {
            return this.isCostResourceField;
        }
        set {
            this.isCostResourceField = value;
        }
    }
    
    /// <remarks/>
    public string IsBudget {
        get {
            return this.isBudgetField;
        }
        set {
            this.isBudgetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectAssignmentsAssignment {
    
    private string uIDField;
    
    private string gUIDField;
    
    private string taskUIDField;
    
    private string resourceUIDField;
    
    private string percentWorkCompleteField;
    
    private string actualCostField;
    
    private string actualOvertimeCostField;
    
    private string actualOvertimeWorkField;
    
    private string actualWorkField;
    
    private string aCWPField;
    
    private string confirmedField;
    
    private string costField;
    
    private string costRateTableField;
    
    private string rateScaleField;
    
    private string costVarianceField;
    
    private string cvField;
    
    private string delayField;
    
    private string finishField;
    
    private string finishVarianceField;
    
    private string workVarianceField;
    
    private string hasFixedRateUnitsField;
    
    private string fixedMaterialField;
    
    private string levelingDelayField;
    
    private string levelingDelayFormatField;
    
    private string linkedFieldsField;
    
    private string milestoneField;
    
    private string overallocatedField;
    
    private string overtimeCostField;
    
    private string overtimeWorkField;
    
    private string regularWorkField;
    
    private string remainingCostField;
    
    private string remainingOvertimeCostField;
    
    private string remainingOvertimeWorkField;
    
    private string remainingWorkField;
    
    private string responsePendingField;
    
    private string startField;
    
    private string startVarianceField;
    
    private string unitsField;
    
    private string updateNeededField;
    
    private string vACField;
    
    private string workField;
    
    private string workContourField;
    
    private string bCWSField;
    
    private string bCWPField;
    
    private string bookingTypeField;
    
    private string creationDateField;
    
    private string budgetCostField;
    
    private string budgetWorkField;
    
    private ProjectAssignmentsAssignmentTimephasedData[] timephasedDataField;
    
    /// <remarks/>
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string TaskUID {
        get {
            return this.taskUIDField;
        }
        set {
            this.taskUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ResourceUID {
        get {
            return this.resourceUIDField;
        }
        set {
            this.resourceUIDField = value;
        }
    }
    
    /// <remarks/>
    public string PercentWorkComplete {
        get {
            return this.percentWorkCompleteField;
        }
        set {
            this.percentWorkCompleteField = value;
        }
    }
    
    /// <remarks/>
    public string ActualCost {
        get {
            return this.actualCostField;
        }
        set {
            this.actualCostField = value;
        }
    }
    
    /// <remarks/>
    public string ActualOvertimeCost {
        get {
            return this.actualOvertimeCostField;
        }
        set {
            this.actualOvertimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string ActualOvertimeWork {
        get {
            return this.actualOvertimeWorkField;
        }
        set {
            this.actualOvertimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string ActualWork {
        get {
            return this.actualWorkField;
        }
        set {
            this.actualWorkField = value;
        }
    }
    
    /// <remarks/>
    public string ACWP {
        get {
            return this.aCWPField;
        }
        set {
            this.aCWPField = value;
        }
    }
    
    /// <remarks/>
    public string Confirmed {
        get {
            return this.confirmedField;
        }
        set {
            this.confirmedField = value;
        }
    }
    
    /// <remarks/>
    public string Cost {
        get {
            return this.costField;
        }
        set {
            this.costField = value;
        }
    }
    
    /// <remarks/>
    public string CostRateTable {
        get {
            return this.costRateTableField;
        }
        set {
            this.costRateTableField = value;
        }
    }
    
    /// <remarks/>
    public string RateScale {
        get {
            return this.rateScaleField;
        }
        set {
            this.rateScaleField = value;
        }
    }
    
    /// <remarks/>
    public string CostVariance {
        get {
            return this.costVarianceField;
        }
        set {
            this.costVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string CV {
        get {
            return this.cvField;
        }
        set {
            this.cvField = value;
        }
    }
    
    /// <remarks/>
    public string Delay {
        get {
            return this.delayField;
        }
        set {
            this.delayField = value;
        }
    }
    
    /// <remarks/>
    public string Finish {
        get {
            return this.finishField;
        }
        set {
            this.finishField = value;
        }
    }
    
    /// <remarks/>
    public string FinishVariance {
        get {
            return this.finishVarianceField;
        }
        set {
            this.finishVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string WorkVariance {
        get {
            return this.workVarianceField;
        }
        set {
            this.workVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string HasFixedRateUnits {
        get {
            return this.hasFixedRateUnitsField;
        }
        set {
            this.hasFixedRateUnitsField = value;
        }
    }
    
    /// <remarks/>
    public string FixedMaterial {
        get {
            return this.fixedMaterialField;
        }
        set {
            this.fixedMaterialField = value;
        }
    }
    
    /// <remarks/>
    public string LevelingDelay {
        get {
            return this.levelingDelayField;
        }
        set {
            this.levelingDelayField = value;
        }
    }
    
    /// <remarks/>
    public string LevelingDelayFormat {
        get {
            return this.levelingDelayFormatField;
        }
        set {
            this.levelingDelayFormatField = value;
        }
    }
    
    /// <remarks/>
    public string LinkedFields {
        get {
            return this.linkedFieldsField;
        }
        set {
            this.linkedFieldsField = value;
        }
    }
    
    /// <remarks/>
    public string Milestone {
        get {
            return this.milestoneField;
        }
        set {
            this.milestoneField = value;
        }
    }
    
    /// <remarks/>
    public string Overallocated {
        get {
            return this.overallocatedField;
        }
        set {
            this.overallocatedField = value;
        }
    }
    
    /// <remarks/>
    public string OvertimeCost {
        get {
            return this.overtimeCostField;
        }
        set {
            this.overtimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string OvertimeWork {
        get {
            return this.overtimeWorkField;
        }
        set {
            this.overtimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string RegularWork {
        get {
            return this.regularWorkField;
        }
        set {
            this.regularWorkField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingCost {
        get {
            return this.remainingCostField;
        }
        set {
            this.remainingCostField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingOvertimeCost {
        get {
            return this.remainingOvertimeCostField;
        }
        set {
            this.remainingOvertimeCostField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingOvertimeWork {
        get {
            return this.remainingOvertimeWorkField;
        }
        set {
            this.remainingOvertimeWorkField = value;
        }
    }
    
    /// <remarks/>
    public string RemainingWork {
        get {
            return this.remainingWorkField;
        }
        set {
            this.remainingWorkField = value;
        }
    }
    
    /// <remarks/>
    public string ResponsePending {
        get {
            return this.responsePendingField;
        }
        set {
            this.responsePendingField = value;
        }
    }
    
    /// <remarks/>
    public string Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    public string StartVariance {
        get {
            return this.startVarianceField;
        }
        set {
            this.startVarianceField = value;
        }
    }
    
    /// <remarks/>
    public string Units {
        get {
            return this.unitsField;
        }
        set {
            this.unitsField = value;
        }
    }
    
    /// <remarks/>
    public string UpdateNeeded {
        get {
            return this.updateNeededField;
        }
        set {
            this.updateNeededField = value;
        }
    }
    
    /// <remarks/>
    public string VAC {
        get {
            return this.vACField;
        }
        set {
            this.vACField = value;
        }
    }
    
    /// <remarks/>
    public string Work {
        get {
            return this.workField;
        }
        set {
            this.workField = value;
        }
    }
    
    /// <remarks/>
    public string WorkContour {
        get {
            return this.workContourField;
        }
        set {
            this.workContourField = value;
        }
    }
    
    /// <remarks/>
    public string BCWS {
        get {
            return this.bCWSField;
        }
        set {
            this.bCWSField = value;
        }
    }
    
    /// <remarks/>
    public string BCWP {
        get {
            return this.bCWPField;
        }
        set {
            this.bCWPField = value;
        }
    }
    
    /// <remarks/>
    public string BookingType {
        get {
            return this.bookingTypeField;
        }
        set {
            this.bookingTypeField = value;
        }
    }
    
    /// <remarks/>
    public string CreationDate {
        get {
            return this.creationDateField;
        }
        set {
            this.creationDateField = value;
        }
    }
    
    /// <remarks/>
    public string BudgetCost {
        get {
            return this.budgetCostField;
        }
        set {
            this.budgetCostField = value;
        }
    }
    
    /// <remarks/>
    public string BudgetWork {
        get {
            return this.budgetWorkField;
        }
        set {
            this.budgetWorkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TimephasedData")]
    public ProjectAssignmentsAssignmentTimephasedData[] TimephasedData {
        get {
            return this.timephasedDataField;
        }
        set {
            this.timephasedDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectAssignmentsAssignmentTimephasedData {
    
    private string typeField;
    
    private string uIDField;
    
    private string startField;
    
    private string finishField;
    
    private string unitField;
    
    private string valueField;
    
    /// <remarks/>
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    public string Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    public string Finish {
        get {
            return this.finishField;
        }
        set {
            this.finishField = value;
        }
    }
    
    /// <remarks/>
    public string Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectBoardColumnsBoardColumn {
    
    private string uIDField;
    
    private string gUIDField;
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
public partial class ProjectSprintsSprint {
    
    private string uIDField;
    
    private string gUIDField;
    
    private string idField;
    
    private string nameField;
    
    private string startField;
    
    private string finishField;
    
    private string durationUnitsField;
    
    private string durationField;
    
    /// <remarks/>
    public string UID {
        get {
            return this.uIDField;
        }
        set {
            this.uIDField = value;
        }
    }
    
    /// <remarks/>
    public string GUID {
        get {
            return this.gUIDField;
        }
        set {
            this.gUIDField = value;
        }
    }
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Start {
        get {
            return this.startField;
        }
        set {
            this.startField = value;
        }
    }
    
    /// <remarks/>
    public string Finish {
        get {
            return this.finishField;
        }
        set {
            this.finishField = value;
        }
    }
    
    /// <remarks/>
    public string DurationUnits {
        get {
            return this.durationUnitsField;
        }
        set {
            this.durationUnitsField = value;
        }
    }
    
    /// <remarks/>
    public string Duration {
        get {
            return this.durationField;
        }
        set {
            this.durationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2558.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.microsoft.com/project")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/project", IsNullable=false)]
public partial class NewDataSet {
    
    private Project[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Project")]
    public Project[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
