//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTerminal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjectTerminal.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleared all supporting data.
        /// </summary>
        internal static string general_clean_Complete {
            get {
                return ResourceManager.GetString("general.clean.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization complete {0}.
        /// </summary>
        internal static string general_initialize_Complete {
            get {
                return ResourceManager.GetString("general.initialize.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Chromium.
        /// </summary>
        internal static string general_initialize_Download {
            get {
                return ResourceManager.GetString("general.initialize.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to install.
        /// </summary>
        internal static string general_install_CompleteFailure {
            get {
                return ResourceManager.GetString("general.install.CompleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium revision {0} installed.
        /// </summary>
        internal static string general_install_CompleteSuccess {
            get {
                return ResourceManager.GetString("general.install.CompleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Chromium.
        /// </summary>
        internal static string general_install_Download {
            get {
                return ResourceManager.GetString("general.install.Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium revision {0}.
        /// </summary>
        internal static string general_installed_ChromiumVersion {
            get {
                return ResourceManager.GetString("general.installed.ChromiumVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium not installed.
        /// </summary>
        internal static string general_installed_NotInstalled {
            get {
                return ResourceManager.GetString("general.installed.NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Chromium revision {0}.
        /// </summary>
        internal static string general_uninstall_RemovedRevision {
            get {
                return ResourceManager.GetString("general.uninstall.RemovedRevision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannnot coerce the input argument {0} to required type {1}.
        /// </summary>
        internal static string program_coerce_FailedToCoerce {
            get {
                return ResourceManager.GetString("program.coerce.FailedToCoerce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized command &apos;{0}.{1}&apos;. Please type a valid command..
        /// </summary>
        internal static string program_execute_BadCommand {
            get {
                return ResourceManager.GetString("program.execute.BadCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing required argument. {0} required, {1} optional, {2} provided.
        /// </summary>
        internal static string program_execute_MissingParameters {
            get {
                return ResourceManager.GetString("program.execute.MissingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value passed for argument &apos;{0}&apos; cannot be parsed to type &apos;{1}&apos;.
        /// </summary>
        internal static string program_execute_UnableToParseArg {
            get {
                return ResourceManager.GetString("program.execute.UnableToParseArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Operations Terminal.
        /// </summary>
        internal static string program_main_Banner {
            get {
                return ResourceManager.GetString("program.main.Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes interactive and script based actions against your instance.
        /// </summary>
        internal static string program_main_Description {
            get {
                return ResourceManager.GetString("program.main.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing from script {0}.
        /// </summary>
        internal static string program_main_ExecScript {
            get {
                return ResourceManager.GetString("program.main.ExecScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found {0}.
        /// </summary>
        internal static string program_main_FileNotFound {
            get {
                return ResourceManager.GetString("program.main.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete {0} lines processed.
        /// </summary>
        internal static string program_main_ProcessedLines {
            get {
                return ResourceManager.GetString("program.main.ProcessedLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium not installed.
        /// </summary>
        internal static string project_install_failed {
            get {
                return ResourceManager.GetString("project.install.failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromium revision {0} installed.
        /// </summary>
        internal static string project_install_Success {
            get {
                return ResourceManager.GetString("project.install.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login successful.
        /// </summary>
        internal static string project_login_Success {
            get {
                return ResourceManager.GetString("project.login.Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token not found.
        /// </summary>
        internal static string project_login_TokenNotFound {
            get {
                return ResourceManager.GetString("project.login.TokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login before you open a project.
        /// </summary>
        internal static string project_open_ErrLoginBeforeOpen {
            get {
                return ResourceManager.GetString("project.open.ErrLoginBeforeOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project opened.
        /// </summary>
        internal static string project_open_ProjectOpen {
            get {
                return ResourceManager.GetString("project.open.ProjectOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open project prior to adding tasks.
        /// </summary>
        internal static string project_task_ErrOpenBeforeAdd {
            get {
                return ResourceManager.GetString("project.task.ErrOpenBeforeAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task added.
        /// </summary>
        internal static string project_task_TaskAdded {
            get {
                return ResourceManager.GetString("project.task.TaskAdded", resourceCulture);
            }
        }
    }
}
